destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/discography-pdf"
port: 4011
output: pdf
product: discography
print_title: discography documentation
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: discography_sidebar
